### ISSUE TITLE
Deliverable 1

### ISSUE THREAD

**Issue by Clhooper** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-Clhooper#1]
<img width="1017" alt="Screen Shot 2023-11-02 at 9 09 34 PM" src="https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-Clhooper/assets/143145630/54ab47be-58bb-414f-8eae-ed5333a553a6">

**Comment by instructorc** [comment]
Deliverable met!
